backend:
  name: github
  repo: gattcocco/cognitariat
  branch: main
  editorial_workflow: true

media_folder: "public/images/articoli"
public_folder: "/images/articoli"

collections:
  - name: articles
    label: Articoli
    label_singular: Articolo
    folder: src/content/articles
    create: true
    slug: "{{slug}}"
    extension: md
    format: frontmatter
    fields:
      - { label: Titolo, name: title, widget: string }
      - { label: Data, name: date, widget: datetime }
      - { label: Autore, name: autore, widget: string }
      - { label: Estratto, name: excerpt, widget: text }
      - { label: Immagine di copertina, name: cover, widget: image, required: false }
      - { label: Corpo, name: body, widget: markdown }
